export enum PermissaoEnum {
  CAMUNDA = "CAMUNDA",
  DEPARTMENT = "DEPARTMENT",
  ADM = "ADM",
  AUS = "AUS",
  EUS = "EUS",
  RUS = "RUS",
  CUS = "CUS",
  HIS = "HIS",
  BATCH_READ = "BATCH_READ",
  BATCH_DELETE = "BATCH_DELETE",
  BATCH_CREATE = "BATCH_CREATE",
  DECISIION_DEFINITIO_READ = "DECISIION_DEFINITIO_READ",
  DECISIION_DEFINITIO_DELETE = "DECISIION_DEFINITIO_DELETE",
  DECISIION_DEFINITIO_CREATE = "DECISIION_DEFINITIO_CREATE",
  DECISIION_REQUERIMENTS_READ = "DECISIION_REQUERIMENTS_READ",
  DEPLOY_READ = "DEPLOY_READ",
  DEPLOY_DELETE = "DEPLOY_DELETE",
  DEPLOY_CREATE = "DEPLOY_CREATE",
  FILTER_READ = "FILTER_READ",
  FILTER_DELETE = "FILTER_DELETE",
  FILTER_CREATE = "FILTER_CREATE",
  GROUP_READ = "GROUP_READ",
  GROUP_DELETE = "GROUP_DELETE",
  GROUP_CREATE = "GROUP_CREATE",
  HISTORIC_PROCESS_READ = "HISTORIC_PROCESS_READ",
  HISTORIC_TASK_READ = "HISTORIC_TASK_READ",
  LOG_READ = "LOG_READ",
  LOG_DELETE = "LOG_DELETE",
  LOG_UPDATE = "LOG_UPDATE",
  PROCESS_DEFINITION_READ = "PROCESS_DEFINITION_READ",
  PROCESS_DEFINITION_DELETE = "PROCESS_DEFINITION_DELETE",
  UPDATE_INSTANCE_VARIABLE = "UPDATE_INSTANCE_VARIABLE",
  PROCESS_DEFINITION_CREATE = "PROCESS_DEFINITION_CREATE",
  PROCESS_INSTANCE_READ = "PROCESS_INSTANCE_READ",
  PROCESS_INSTANCE_DELETE = "PROCESS_INSTANCE_DELETE",
  PROCESS_INSTANCE_CREATE = "PROCESS_INSTANCE_CREATE",
  TASK_ASSIGN = "TASK_ASSIGN",
  TASK_READ = "TASK_READ",
  TASK_DELETE = "TASK_DELETE",
  TASK_CREATE = "TASK_CREATE"
}

export const PermissaoEnumDescriptions: Record<PermissaoEnum, string> = {
  [PermissaoEnum.CAMUNDA]: "Grupos de autorização camunda",
  [PermissaoEnum.DEPARTMENT]: "Grupos de departamentos",
  [PermissaoEnum.ADM]: "Administrador",
  [PermissaoEnum.AUS]: "Administrar usuários",
  [PermissaoEnum.EUS]: "Editar usuários",
  [PermissaoEnum.RUS]: "Remover usuários",
  [PermissaoEnum.CUS]: "Cria usuários",
  [PermissaoEnum.HIS]: "Ver histórico",
  [PermissaoEnum.BATCH_READ]: "Ler lotes",
  [PermissaoEnum.BATCH_DELETE]: "Remover lotes",
  [PermissaoEnum.BATCH_CREATE]: "Criar atualizar lotes",
  [PermissaoEnum.DECISIION_DEFINITIO_READ]: "Ver decisões",
  [PermissaoEnum.DECISIION_DEFINITIO_DELETE]: "Remover decisões",
  [PermissaoEnum.DECISIION_DEFINITIO_CREATE]: "Criar atualizar decisões",
  [PermissaoEnum.DECISIION_REQUERIMENTS_READ]: "Ler requerimentos de decisões",
  [PermissaoEnum.DEPLOY_READ]: "Ver implantações",
  [PermissaoEnum.DEPLOY_DELETE]: "Remover implantações",
  [PermissaoEnum.DEPLOY_CREATE]: "Criar atualizar implantações",
  [PermissaoEnum.FILTER_READ]: "Ver filtros",
  [PermissaoEnum.FILTER_DELETE]: "Remover filtros",
  [PermissaoEnum.FILTER_CREATE]: "Criar atualizar filtros",
  [PermissaoEnum.GROUP_READ]: "Ver departamentos",
  [PermissaoEnum.GROUP_DELETE]: "Remover departamentos",
  [PermissaoEnum.GROUP_CREATE]: "Criar atualizar departamentos",
  [PermissaoEnum.HISTORIC_PROCESS_READ]: "Ver históricos de processos",
  [PermissaoEnum.HISTORIC_TASK_READ]: "Ver históricos de tarefas",
  [PermissaoEnum.LOG_READ]: "Ver logs",
  [PermissaoEnum.LOG_DELETE]: "Remover logs",
  [PermissaoEnum.LOG_UPDATE]: "Atualizar logs",
  [PermissaoEnum.PROCESS_DEFINITION_READ]: "Ver definições de processos",
  [PermissaoEnum.PROCESS_DEFINITION_DELETE]: "Remover definições de processos",
  [PermissaoEnum.UPDATE_INSTANCE_VARIABLE]: "Atualizar variaveis da instância",
  [PermissaoEnum.PROCESS_DEFINITION_CREATE]: "Criar atualizar definições de processos",
  [PermissaoEnum.PROCESS_INSTANCE_READ]: "Ver instancias de processos",
  [PermissaoEnum.PROCESS_INSTANCE_DELETE]: "Remover instancias de processos",
  [PermissaoEnum.PROCESS_INSTANCE_CREATE]: "Criar atualizar instancias de processos",
  [PermissaoEnum.TASK_ASSIGN]: "Assumir tarefas",
  [PermissaoEnum.TASK_READ]: "Vere tarefas",
  [PermissaoEnum.TASK_DELETE]: "Remover tarefas",
  [PermissaoEnum.TASK_CREATE]: "Criar atualizar tarefas"
};
