import { Translation } from "primeng/api";

export const PT_BR:Translation = {
  "startsWith": "Começa com",
  "contains": "Contém",
  "notContains": "Não contém",
  "endsWith": "Termina com",
  "equals": "Igual a",
  "notEquals": "Diferente de",
  "noFilter": "Sem filtro",
  "lt": "Menor que",
  "lte": "Menor ou igual a",
  "gt": "Maior que",
  "gte": "Maior ou igual a",
  "is": "É",
  "isNot": "Não é",
  "before": "Antes",
  "after": "Depois",
  "dateIs": "A data é",
  "dateIsNot": "A data não é",
  "dateBefore": "A data é antes",
  "dateAfter": "A data é depois",
  "clear": "Limpar",
  "apply": "Aplicar",
  "matchAll": "Combinar todos",
  "matchAny": "Combinar qualquer",
  "addRule": "Adicionar Regra",
  "removeRule": "Remover Regra",
  "accept": "Sim",
  "reject": "Não",
  "choose": "Escolher",
  "upload": "Enviar",
  "cancel": "Cancelar",
  "pending": "Pendente",
  "fileSizeTypes": [
    "B",
    "KB",
    "MB",
    "GB",
    "TB",
    "PB",
    "EB",
    "ZB",
    "YB"
  ],
  "dayNames": [
    "Domingo",
    "Segunda-feira",
    "Terça-feira",
    "Quarta-feira",
    "Quinta-feira",
    "Sexta-feira",
    "Sábado"
  ],
  "dayNamesShort": [
    "Dom",
    "Seg",
    "Ter",
    "Qua",
    "Qui",
    "Sex",
    "Sáb"
  ],
  "dayNamesMin": [
    "Do",
    "Se",
    "Te",
    "Qa",
    "Qi",
    "Sx",
    "Sa"
  ],
  "monthNames": [
    "Janeiro",
    "Fevereiro",
    "Março",
    "Abril",
    "Maio",
    "Junho",
    "Julho",
    "Agosto",
    "Setembro",
    "Outubro",
    "Novembro",
    "Dezembro"
  ],
  "monthNamesShort": [
    "Jan",
    "Fev",
    "Mar",
    "Abr",
    "Mai",
    "Jun",
    "Jul",
    "Ago",
    "Set",
    "Out",
    "Nov",
    "Dez"
  ],
  "chooseYear": "Escolher ano",
  "chooseMonth": "Escolher mês",
  "chooseDate": "Escolher data",
  "prevDecade": "Década anterior",
  "nextDecade": "Próxima década",
  "prevYear": "Ano anterior",
  "nextYear": "Próximo ano",
  "prevMonth": "Mês anterior",
  "nextMonth": "Próximo mês",
  "prevHour": "Hora anterior",
  "nextHour": "Próxima hora",
  "prevMinute": "Minuto anterior",
  "nextMinute": "Próximo minuto",
  "prevSecond": "Segundo anterior",
  "nextSecond": "Próximo segundo",
  "am": "AM",
  "pm": "PM",
  "dateFormat": "dd/mm/yy",
  "firstDayOfWeek": 0,
  "today": "Hoje",
  "weekHeader": "Sm",
  "weak": "Fraca",
  "medium": "Média",
  "strong": "Forte",
  "passwordPrompt": "Digite uma senha",
  "emptyMessage": "Nenhum resultado encontrado",
  "searchMessage": "Resultados disponíveis",
  "selectionMessage": "{0} itens selecionados",
  "emptySelectionMessage": "Nenhum item selecionado",
  "emptySearchMessage": "Nenhum resultado encontrado",
  "emptyFilterMessage": "Nenhum resultado encontrado",
  "fileChosenMessage": "Arquivos",
  "noFileChosenMessage": "Nenhum arquivo selecionado",
  "aria": {
    "trueLabel": "Verdadeiro",
    "falseLabel": "Falso",
    "nullLabel": "Não selecionado",
    "star": "1 estrela",
    "stars": "{star} estrelas",
    "selectAll": "Todos os itens selecionados",
    "unselectAll": "Todos os itens desmarcados",
    "close": "Fechar",
    "previous": "Anterior",
    "next": "Próximo",
    "navigation": "Navegação",
    "scrollTop": "Voltar ao topo",
    "moveTop": "Mover para o topo",
    "moveUp": "Mover para cima",
    "moveDown": "Mover para baixo",
    "moveBottom": "Mover para o final",
    "moveToTarget": "Mover para o destino",
    "moveToSource": "Mover para a origem",
    "moveAllToTarget": "Mover tudo para o destino",
    "moveAllToSource": "Mover tudo para a origem",
    "pageLabel": "{page}",
    "firstPageLabel": "Primeira página",
    "lastPageLabel": "Última página",
    "nextPageLabel": "Próxima página",
    "prevPageLabel": "Página anterior",
    "rowsPerPageLabel": "Linhas por página",
    "previousPageLabel": "Página anterior",
    "jumpToPageDropdownLabel": "Ir para página (menu)",
    "jumpToPageInputLabel": "Ir para página (campo)",
    "selectRow": "Linha selecionada",
    "unselectRow": "Linha desmarcada",
    "expandRow": "Linha expandida",
    "collapseRow": "Linha recolhida",
    "showFilterMenu": "Mostrar filtro",
    "hideFilterMenu": "Ocultar filtro",
    "filterOperator": "Operador de filtro",
    "filterConstraint": "Condição de filtro",
    "editRow": "Editar linha",
    "saveEdit": "Salvar edição",
    "cancelEdit": "Cancelar edição",
    "listView": "Visualização em lista",
    "gridView": "Visualização em grade",
    "slide": "Slide",
    "slideNumber": "Slide {slideNumber}",
    "zoomImage": "Zoom da imagem",
    "zoomIn": "Ampliar",
    "zoomOut": "Reduzir",
    "rotateRight": "Girar à direita",
    "rotateLeft": "Girar à esquerda",
    "listLabel": "Lista de opções",
    "selectColor": "Selecionar uma cor",
    "removeLabel": "Remover",
    "browseFiles": "Procurar arquivos",
    "maximizeLabel": "Maximizar"
  }
}
